const Router = require("express").Router()
const MaincategoryRouter = require("./maincategory.route")
const SubcategoryRouter = require("./subcategory.route")
const BrandRouter = require("./brand.route")
const FeatureRouter = require("./feature.route")
const FaqRouter = require("./faq.route")
const SettingRouter = require("./setting.route")
const ProductRouter = require("./product.route")
const UserRouter = require("./user.route")
const CartRouter = require("./cart.route")
const WishlistRouter = require("./wishlist.route")
const CheckoutRouter = require("./checkout.route")
const NewsletterRouter = require("./newsletter.route")
const ContactusRouter = require("./contactus.route")
const TestimonialRouter = require("./testimonial.route")


Router.use("/maincategory", MaincategoryRouter)
Router.use("/subcategory", SubcategoryRouter)
Router.use("/brand", BrandRouter)
Router.use("/feature", FeatureRouter)
Router.use("/faq", FaqRouter)
Router.use("/setting", SettingRouter)
Router.use("/product", ProductRouter)
Router.use("/user", UserRouter)
Router.use("/cart", CartRouter)
Router.use("/wishlist", WishlistRouter)
Router.use("/checkout", CheckoutRouter)
Router.use("/newsletter", NewsletterRouter)
Router.use("/contactus", ContactusRouter)
Router.use("/testimonial", TestimonialRouter)


module.exports = Router